version: '3.0'

services:
  db:
    image: postgres:16.3
    container_name: postgres-db
    environment:
      POSTGRES_DB: social
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: socialpassword

    volumes:
      - db-data:/var/lib/postgresql/data
     # - ./scrips:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

volumes:
  db-data: